@startuml

MainViewController --|> MainView

MainView --|> SFNotificationStack
MainView --|> MenuSidebarController
MainView --|> ItemPanelController

MenuSidebarController --|> MenuSidebar
MenuSidebarController --|> DialogImportFiles
MenuSidebarController --|> DialogCreateCollectionController
MenuSidebarController --|> DialogDeleteCollectionController
MenuSidebarController --|> DialogRenameCollectionController
MenuSidebarController --|> DialogCreateGroupController
MenuSidebarController --|> DialogDeleteGroupController
MenuSidebarController --|> DialogRenameGroupController

MenuSidebar --|> CollectionContextMenu
MenuSidebar --|> GroupContextMenu
MenuSidebar --|> SidebarMenu
SidebarMenu --|> SidebarMenuSection_actions
SidebarMenu --|> SidebarMenuSection_collections
SidebarMenuSection_actions --|> MenuActionImport
SidebarMenuSection_actions --|> MenuActionRefresh
SidebarMenuSection_actions --|> MenuActionClose
SidebarMenuSection_collections --|> CollectionSectionAction
SidebarMenuSection_collections --|> CollectionEntry
SidebarMenuSection_collections --|> GroupEntry
GroupEntry --|> GroupEntry
GroupEntry --|> CollectionEntry


ItemPanelController --|> ItemPanel
ItemPanel --|> Item
ItemPanel --|> ItemContextMenu


@enduml